version: 0.2
phases:
  install:
    commands:
      - pwd
  pre_build:
    commands:
      - echo Pre Build started on `date`
      - echo CODEBUILD_SOURCE_VERSION $(CODEBUILD_SOURCE_VERSION)
      - curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - unzip -o terraform.zip -d /usr/bin
  build:
    commands:
      - echo Build started on `date`
      - echo Command ${COMMAND}
      - echo Environment ${ENVIRONMENT}
      - echo Role ARN ${CLIENT_ROLE_ARN}
      - ls -al
      - make ${COMMAND} ENVIRONMENT=${ENVIRONMENT} CLIENT_ROLE_ARN=${CLIENT_ROLE_ARN}
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/*
    - plan/*
    - buildspec.yml
    - assume_role.sh
    - Makefile
    - terraform/**/*
  discard-paths: no
cache:
  paths:
    - '/go/pkg/**/*'